### ISSUE TITLE
How can I add comics

### ISSUE THREAD

**Issue by lpf260** [mangapress/mangapress#103]
I used this plugin, but I don't know how to add comics.
Next it is my blog capture. I can only add one photo. Thanks, Looking forward to your reply.
![image](https://user-images.githubusercontent.com/8652062/100730078-8ae97000-3404-11eb-8ec7-d94611b1a90e.png)

**Comment by jesgs** [comment]
Each Comic is actually it's own post. So to add another comic, you need to click "Add New" again. The reason for this is so that I can make use of WordPress' per-post navigation functions to create the navigation between comics. From there, you can divide your comics into Series. Hope this helps!
